In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

Neste módulo, vamos trabalhar com um array 3-D, que representa o desempenho de atletas de corrida.

Na primeira dimensão (profundidade), vamos representar 3 dias de avaliação diferentes. Na segunda dimensão (linhas), cada um dos 5 atletas. Na terceira dimensão (colunas), cada uma das 4 voltas da pista de corrida. Os valores serão dados em segundos.

Estes dados serão simulados com o código abaixo, mas não se preocupe em entendê-lo por enquanto, os detalhes destas funções serão apresentados nas próximas aulas.

In [3]:
rng = np.random.default_rng(seed=1)

In [4]:
array = rng.normal(loc=50, scale=3, size=60).reshape(3, 5, 4).round(3)

In [5]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [6]:
array.shape

(3, 5, 4)

👆 Observe pelo `shape` que são 3 dias, 5 atletas e 4 voltas.

Dada a definição deste array apresentada acima, você pode entender a primeira linha:
```
[51.037, 52.465, 50.991, 46.091]
```
como o desempenho do primeiro atleta, no primeiro dia, nas 4 voltas da pista.

A sétima linha:
```
[41.867, 44.333, 49.476, 48.733]
```
é o desempenho do segundo atleta no segundo dia, nas 4 voltas da pista.

### Indexing

Dado o array acima, utilize indexação para recuperar o desempenho do terceiro atleta no segundo dia.

Lembre-se que, no Python, a indexação começa em 0!

In [7]:
array[1][2]

array([50.641, 50.652, 56.354, 46.664])

Agora recupere o desempenho de todos os atletas na última volta do primeiro dia. Use indexação negativa para acessar a última volta.

In [8]:
array[0,:,-1]

array([46.091, 51.743, 51.64 , 51.797, 49.228])

In [9]:
array[0,:,3]

array([46.091, 51.743, 51.64 , 51.797, 49.228])

Agora recupere o desempenho do segundo e do quarto atletas, no terceiro dia, na segunda volta.

In [10]:
array[2,1:4:2,1]

array([50.286, 48.496])

Usando indexação negativa, recupere o desempenho de todos os atletas em todos os dias, na penúltima volta.

In [11]:
array[0:3,:,-2]

array([[50.991, 48.389, 50.085, 48.554, 47.654],
       [53.882, 49.476, 56.354, 51.94 , 50.502],
       [49.784, 50.107, 50.963, 52.637, 46.254]])

Crie uma máscara booleana para representar somente os resultados menores que 46. Depois utilize esta máscara para filtrar do array os resultados que atendem a esta condição.

In [12]:
mask = array < 46

In [13]:
mask
array[mask]

array([41.867, 44.333, 45.056])

### Slicing

Utilize fatiamento para recuperar o desempenho do quarto atleta nas duas primeiras voltas, em todos os dias.

In [14]:
array[0:3,3,0:2]

array([[47.791, 49.511],
       [48.867, 56.128],
       [52.195, 48.496]])

Agora recupere o desempenho de todos os atletas nos dois primeiros dias, da segunda volta em diante.

In [15]:
array[0:2,:,1:]

array([[[52.465, 50.991, 46.091],
        [51.339, 48.389, 51.743],
        [50.882, 50.085, 51.64 ],
        [49.511, 48.554, 51.797],
        [49.123, 47.654, 49.228]],

       [[49.173, 53.882, 53.02 ],
        [44.333, 49.476, 48.733],
        [50.652, 56.354, 46.664],
        [56.128, 51.94 , 51.989],
        [45.056, 50.502, 50.327]]])

Utilize a notação negativa e a notação de "passo" para recuperar os desempenhos dos dois últimos atletas, no segundo dia, nas voltas de índice ímpar.

In [16]:
array[1,-2:,1::2]

array([[56.128, 51.989],
       [45.056, 50.327]])

In [17]:
array[1,3:5,1:3]

array([[56.128, 51.94 ],
       [45.056, 50.502]])

### Assigning

Suponha que o segundo atleta tenha sido desclassificado na prova do terceiro dia, e você deve demonstrar isso no array mudando todos os valores de suas voltas para o número 99.

Utilize a técnica de assigning para fazer esta correção, e exiba o array modificado.

In [18]:
array[2][1] = 99

In [19]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

Foi descoberto que o cronômetro utilizado no primeiro dia de prova estava descalibrado, e por isso, todos os tempos correspondentes devem ser acrescidos em 0.05 segundos. Realize a correção e exiba o array modificado.

Lembre-se que você pode adicionar valores a um objeto do Python com a notação `+=`.

In [20]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [21]:
array[0] += 0.05

In [22]:
array

array([[[51.087, 52.515, 51.041, 46.141],
        [52.766, 51.389, 48.439, 51.793],
        [51.144, 50.932, 50.135, 51.69 ],
        [47.841, 49.561, 48.604, 51.847],
        [50.169, 49.173, 47.704, 49.278]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

A terceira volta dos dois primeiros atletas no segundo dia foi registrada errada, os valores corretos são 53.872 e 49.479. Faça a correção e exiba o array modificado.

In [29]:
array[1,0:2,2] = [53.872,49.479]

In [30]:
array

array([[[51.087, 52.515, 51.041, 46.141],
        [52.766, 51.389, 48.439, 51.793],
        [51.144, 50.932, 50.135, 51.69 ],
        [47.841, 49.561, 48.604, 51.847],
        [50.169, 49.173, 47.704, 49.278]],

       [[50.024, 49.173, 53.872, 53.02 ],
        [41.867, 44.333, 49.479, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])